//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public string ID { get; set; }
        public string IDHoaDon { get; set; }
        public string IDObject { get; set; }
        public int Counts { get; set; }
        public double Price { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual VatLieu VatLieu { get; set; }
    }
}
