//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int STT { get; set; }
        public string ID { get; set; }
        public string IDObject { get; set; }
        public string IDINput { get; set; }
        public Nullable<int> Counts { get; set; }
        public Nullable<double> PriceInput { get; set; }
        public Nullable<double> PriceOutput { get; set; }
        public string Status { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual VatLieu VatLieu { get; set; }
    }
}
