//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int MaCTPN { get; set; }
        public Nullable<int> MaPhieuNhap { get; set; }
        public Nullable<int> MaVatLieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaNhap { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual VatLieu VatLieu { get; set; }
    }
}
