//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaVatLieu
    {
        public int ID { get; set; }
        public string IDVatLieu { get; set; }
        public Nullable<double> GiaCu { get; set; }
        public double GiaMoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoi { get; set; }
        public string NguoiThayDoi { get; set; }
    
        public virtual VatLieu VatLieu { get; set; }
    }
}
