//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyVatLieuXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi
    {
        public string ID { get; set; }
        public string IDNhaCungCap { get; set; }
        public Nullable<System.DateTime> NgayChi { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string NoiDung { get; set; }
        public string IDUser { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
